Numpy Assignment

In [82]:
import numpy as np

Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [94]:
def find_moving_average(data,k):
    newdata = []
    data_array = np.array(data)
    for i in range (0,data_array.size-(k-1)):
        newdata.append(data_array[i:i+k])
    newdata_array = np.array(newdata)
    iterable = [np.average(i) for i in newdata_array]
    values = np.fromiter(iterable,dtype = 'float')
    return values.size


In [95]:
data = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k=3
avg_sequence =  find_moving_average(data,k)
print("average sequence has ",avg_sequence)
N = len(data)
print("average sequence has n-k+1=",N-k+1 )

average sequence has  11
average sequence has n-k+1= 11


Write a function so that the columns of the output matrix are powers of the input
vector.

In [85]:
x = np.array([1,2,3,4,5])
N = 5
def geometric_progression_matrix(values,N):
    return np.column_stack([x**(N-i-1) for i in range(N)])
values = geometric_progression_matrix(x,N)
print(values)
print(np.linalg.det(values))

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
287.9999999999962


In [86]:
y = np.vander(x, N)
print(y)
print(np.linalg.det(y))

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
287.9999999999962
